# Generated by Django 5.2.13 on 2026-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(default='Участник', help_text='Например: тимлид, дизайнер, аналитик, backend-разработчик', max_length=100, verbose_name='Роль в проекте'),
        ),
    ]
