# Generated by Django 5.2.13 on 2026-04-29 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectfolder_projectfile_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfolder',
            options={'verbose_name': 'Папка проекта', 'verbose_name_plural': 'Папки проекта'},
        ),
        migrations.AddField(
            model_name='projectfolder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_folders', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='projectfolder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название папки'),
        ),
        migrations.AlterField(
            model_name='projectfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectfolder', verbose_name='Родительская папка'),
        ),
        migrations.AlterField(
            model_name='projectfolder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfolder',
            unique_together={('project', 'parent', 'name')},
        ),
    ]
