# Generated by Django 5.2.13 on 2026-05-04 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projectfolder_options_projectfolder_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название встречи')),
                ('meeting_url', models.URLField(verbose_name='Ссылка на встречу')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время встречи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Созвон',
                'verbose_name_plural': 'Созвоны',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
