# Generated by Django 5.2.13 on 2026-05-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отображаемое название файла'),
        ),
    ]
