# Generated by Django 5.2.13 on 2026-05-14 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Роль в проекте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приглашения')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_project_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Кем приглашён')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Приглашение в проект',
                'verbose_name_plural': 'Приглашения в проекты',
                'unique_together': {('project', 'email')},
            },
        ),
    ]
