# Generated by Django 5.2.13 on 2026-05-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('sick', 'Болел')], default='present', max_length=20),
        ),
    ]
