# Generated by Django 5.2.13 on 2026-05-19 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_attendance_status'),
        ('tasks', '0020_grade_graded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_files', to='tasks.submission', verbose_name='Связанная сдача'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_files', to='tasks.task', verbose_name='Связанная задача'),
        ),
    ]
