# Generated by Django 5.2.13 on 2026-05-19 03:27

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projectfile_submission_projectfile_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfolder',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Путь папки в хранилище'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to=apps.projects.models.project_file_upload_path),
        ),
    ]
