# Generated by Django 5.2.13 on 2026-05-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectfolder_storage_path_alter_projectfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать в файловом хранилище'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Загружен вручную'), ('submission', 'Файл ответа на задачу')], default='manual', max_length=30, verbose_name='Источник файла'),
        ),
    ]
