# Generated by Django 5.2.13 on 2026-04-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус проверки'),
        ),
    ]
