# Generated by Django 5.2.13 on 2026-04-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_submission_checked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_open_for_self_assign',
            field=models.BooleanField(default=False, verbose_name='Доступна для самостоятельного выбора'),
        ),
    ]
