# Generated by Django 5.2.13 on 2026-04-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_taskfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskFile',
        ),
    ]
