# Generated by Django 5.2.13 on 2026-04-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projectfolder_options_projectfolder_created_by_and_more'),
        ('tasks', '0011_delete_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='publish_to_project_files',
            field=models.BooleanField(default=False, verbose_name='Опубликовать файл в материалы проекта'),
        ),
        migrations.AddField(
            model_name='submission',
            name='target_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='projects.projectfolder', verbose_name='Папка для публикации'),
        ),
    ]
