# Generated by Django 5.2.13 on 2026-05-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.submission', verbose_name='Сдача задания')),
            ],
            options={
                'verbose_name': 'Файл сдачи',
                'verbose_name_plural': 'Файлы сдач',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
