# Generated by Django 5.2.13 on 2026-05-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('in_progress', 'В работе'), ('review', 'Нужна проверка'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('overdue', 'Просрочено')], default='created', max_length=20),
        ),
    ]
