# Generated by Django 5.2.13 on 2026-05-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='self_assigned',
            field=models.BooleanField(default=False, verbose_name='Взята самостоятельно'),
        ),
    ]
