# Generated by Django 5.2.13 on 2026-05-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_self_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Основание оценки'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tasks.task', verbose_name='Задача'),
        ),
    ]
