# Generated by Django 5.2.13 on 2026-05-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_grade_reason_alter_grade_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('regular', 'Обычная оценка'), ('first_attestation', 'Первая аттестация'), ('second_attestation', 'Вторая аттестация'), ('intermediate_attestation', 'Промежуточная аттестация'), ('semester_total', 'Семестровая оценка')], default='regular', max_length=40, verbose_name='Тип оценки'),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.CharField(choices=[('autumn', 'Осенний семестр'), ('spring', 'Весенний семестр')], default='spring', max_length=20, verbose_name='Семестр'),
        ),
    ]
