# Generated by Django 5.2.13 on 2026-05-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_grade_grade_type_grade_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='graded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
