# Generated by Django 5.2.13 on 2026-05-19 03:27

import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_grade_graded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.tasks.models.submission_file_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(upload_to=apps.tasks.models.submission_file_upload_path, verbose_name='Файл'),
        ),
    ]
