# Generated by Django 5.2.13 on 2026-05-19 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectfolder_storage_path_alter_projectfile_file'),
        ('tasks', '0021_alter_submission_file_alter_submissionfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='project_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_file', to='projects.projectfile', verbose_name='Файл проекта'),
        ),
    ]
