# Generated by Django 5.2.13 on 2026-05-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_submissionfile_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionfile',
            name='project_file',
        ),
    ]
