# Generated by Django 5.2.13 on 2026-05-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectfile_is_visible_projectfile_source_type'),
        ('tasks', '0023_remove_submissionfile_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionfile',
            name='file',
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='project_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='projects.projectfile', verbose_name='Файл проекта'),
        ),
    ]
